" ==================================================
" CywVim v1.0
" Configuración principal
" ==================================================

scriptencoding utf-8
set nocompatible

" ==================================================
" Evitar cargar dos veces la configuración
" ==================================================

if exists('g:loaded_cywvim')
    finish
endif

let g:loaded_cywvim = 1

" ==================================================
" Detectar automáticamente la carpeta de CywVim
" ==================================================

let s:base_path    = fnamemodify(expand('<sfile>:p'), ':h')
let s:config_path  = s:base_path . '/config'
let s:plugins_path = s:base_path . '/plugins'
let s:core_path    = s:base_path . '/core'

" ==================================================
" Variables globales
" ==================================================

let g:cywvim_root    = s:base_path
let g:cywvim_config  = s:config_path
let g:cywvim_plugins = s:plugins_path
let g:cywvim_core    = s:core_path

" ==================================================
" Core
" ==================================================

execute 'source ' . s:core_path . '/version.vim'
execute 'source ' . s:core_path . '/messages.vim'
execute 'source ' . s:core_path . '/utils.vim'
execute 'source ' . s:core_path . '/functions.vim'
execute 'source ' . s:core_path . '/health.vim'
execute 'source ' . s:core_path . '/commands.vim'

" ==================================================
" Configuración base
" ==================================================

execute 'source ' . s:config_path . '/general.vim'
execute 'source ' . s:config_path . '/appearance.vim'
execute 'source ' . s:config_path . '/editing.vim'
execute 'source ' . s:config_path . '/search.vim'
execute 'source ' . s:config_path . '/filetypes.vim'

" ==================================================
" Gestión de plugins
" ==================================================

execute 'source ' . s:plugins_path . '/plugins.vim'

" ==================================================
" Configuración de plugins
" ==================================================

execute 'source ' . s:plugins_path . '/colors.vim'
execute 'source ' . s:plugins_path . '/nerdtree.vim'
execute 'source ' . s:plugins_path . '/airline.vim'
execute 'source ' . s:plugins_path . '/git.vim'
execute 'source ' . s:plugins_path . '/autopairs.vim'
execute 'source ' . s:plugins_path . '/coc.vim'
execute 'source ' . s:plugins_path . '/mappings.vim'
