# ==================================================
# CywVim
# Comandos asociados a los paquetes
# Formato:
# paquete=comando
# ==================================================

vim=vim

git=git

curl=curl

ripgrep=rg

fzf=fzf

xclip=xclip

universal-ctags=ctags

fonts-powerline=

build-essential=
