# ==================================================
# CywVim
# Comandos asociados a los paquetes
# Formato:
# paquete=comando
# ==================================================

ripgrep=rg

fzf=fzf

xclip=xclip

wl-clipboard=wl-copy

universal-ctags=ctags

fonts-powerline=

build-essential=
