#==================================================
# CywVim Defaults
#==================================================

INSTALL_DIR="$HOME/.vim"

VIMRC_FILE="$HOME/.vimrc"

PLUG_URL="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

PLUG_FILE="$HOME/.vim/autoload/plug.vim"

COC_TIMEOUT=60
